#!/usr/bin/env bash

VLC=$(command -v cvlc)

if [ -z "${VLC_SOURCE_URL}" ]; then
    echo "Source URL not defined (VLC_SOURCE_URL)"
    exit 1
fi

if [ -z "${VLC_MULTICAST_IP}" ]; then
    VLC_MULTICAST_IP=234.0.0.0
fi

if [ -z "${VLC_MULTICAST_PORT}" ]; then
    VLC_MULTICAST_PORT=1234
fi

if [ -z "${VLC_BITRATE}" ]; then
    VLC_BITRATE=1024
fi

if [ -z "${VLC_CACHE}" ]; then
    VLC_CACHE=1024
fi

if [ -z "${VLC_THREADS}" ]; then
    VLC_THREADS=$(nproc --all)
fi

if [ -z "${VLC_SAP_GROUP}" ]; then
    VLC_SAP_GROUP="Demo Streams"
fi

if [ -z "${VLC_SAP_NAME}" ]; then
    VLC_SAP_NAME="Demo Video"
fi

if [ -z "${VLC_SAP_DESCRIPTION}" ]; then
    VLC_SAP_DESCRIPTION="A demonstration stream."
fi

if [ -z "${VLC_TTL}" ]; then
    VLC_TTL=15
fi

if [ -z "${VLC_ASPECT_RATIO}" ]; then
    VLC_ASPECT_RATIO=16:9
fi

if [ -z "${VLC_ADAPTIVE_WIDTH}" ]; then
    VLC_ADAPTIVE_WIDTH=1280
fi

if [ -z "${VLC_ADAPTIVE_HEIGHT}" ]; then
    VLC_ADAPTIVE_HEIGHT=720
fi

if [ -z "${VLC_ADAPTIVE_BITRATE}" ]; then
    VLC_ADAPTIVE_BITRATE=2048
fi

if [ -z "${VLC_AUDIO_BITRATE}" ]; then
    VLC_AUDIO_BITRATE=192
fi

if [ -z "${VLC_AUDIO_CHANNELS}" ]; then
    VLC_AUDIO_CHANNELS=2
fi

if [ -z "${VLC_ADAPTIVE_LOGIC}" ]; then
    VLC_ADAPTIVE_LOGIC=highest
fi

if [ -z "${VLC_X264}" ]; then
    VLC_X264="preset=ultrafast,tune=zerolatency,keyint=30,bframes=0,ref=1,level=30,profile=baseline,hrd=cbr,crf=20,ratetol=1.0,vbv-maxrate=${VLC_BITRATE},vbv-bufsize=${VLC_BITRATE},lookahead=0"
fi

if [ -z "${VLC_FPS}" ]; then
    VLC_FPS=20
fi

if [ -z "${VLC_RC_PORT}" ]; then
    VLC_RC_PORT=10101
fi

if [ -z "${VLC_VERBOSE}" ]; then
    VLC_VERBOSE=0
fi

if [ -z "${PORT}" ]; then
    PORT=4212
fi

if [ -z "${PASSWORD}" ]; then
    PASSWORD=vlcmulticast
fi

VLC_VENC="x264"
VLC_AENC="ffmpeg"
VLC_VIDEO_CODEC="h264"
VLC_AUDIO_CODEC="mp2a"
VLC_AUDIO_SAMPLERATE="44100"

VLC_SFILTER="audiobargraph_v{barWidth=20,position=1,alarm=1}"
# VLC_AFILTER="audiobargraph_a{bargraph=1,address=127.0.0.1,port=${VLC_RC_PORT},connection_reset=1,bargraph_repetition=22,silence=1,repetition_time=1000,time_window=10000,alarm_threshold=0.01}"
VLC_AFILTER="{audiobargraph_a}"
VLC_VFILTER="canvas{width=${VLC_ADAPTIVE_WIDTH},height=${VLC_ADAPTIVE_HEIGHT},aspect=${VLC_ASPECT_RATIO}}"
# VLC_DESTINATION_STANDARD="'standard{access=udp{caching=1000,ttl=15},mux=ts{use-key-frames},dst=${VLC_MULTICAST_IP}:${VLC_MULTICAST_PORT},sap,group=\"${VLC_SAP_GROUP}\",name=\"${VLC_SAP_NAME}\"}'"
VLC_DESTINATION_RTP="rtp{dst=${VLC_MULTICAST_IP},port=${VLC_MULTICAST_PORT},sdp=sap://,ttl=${VLC_TTL},mux=ts{use-key-frames},proto=udp,name=${VLC_SAP_NAME@Q},description=${VLC_SAP_DESCRIPTION@Q},group=${VLC_SAP_GROUP@Q}}"
VLC_DESTINATION=${VLC_DESTINATION_RTP}
VLC_SCALE="1"

# VLC_EXTRA_OPTIONS_AUDIO_FILTER="--audiobargraph_a-bargraph=1 --audiobargraph_a-bargraph_repetition=1 --audiobargraph_a-silence=1 --audiobargraph_a-repetition_time=1000 --audiobargraph_a-time_window=10000 --audiobargraph_a-alarm_threshold=0.01"
VLC_EXTRA_OPTIONS_AUDIO_FILTER=( "--audiobargraph_a-bargraph" "1" "--audiobargraph_a-bargraph_repetition" "1" "--audiobargraph_a-silence" "1" "--audiobargraph_a-repetition_time" "1000" "--audiobargraph_a-time_window" "10000" "--audiobargraph_a-alarm_threshold" "0.01" )

# VLC_AVCODEC_OPTIONS="--avcodec-dr --avcodec-corrupted --avcodec-hurry-up --avcodec-skip-frame=1 --avcodec-skip-idct=1 --avcodec-fast --avcodec-threads=${VLC_THREADS} --sout-avcodec-strict=-2"
VLC_AVCODEC_OPTIONS=( "--avcodec-dr" "--avcodec-corrupted" "--avcodec-hurry-up" "--avcodec-skip-frame" "1" "--avcodec-skip-idct" "1" "--avcodec-fast" "--avcodec-threads" "${VLC_THREADS}" "--sout-avcodec-strict" "-2" )

if [ -n "$VLC_SFILTER" ]; then
    VLC_SFILTER=",sfilter=${VLC_SFILTER}"
else
    VLC_SFILTER=""
fi

if [ -n "$VLC_AFILTER" ]; then
    VLC_AFILTER=",afilter=${VLC_AFILTER}"
else
    VLC_AFILTER=""
fi

if [ -n "$VLC_VFILTER" ]; then
    VLC_VFILTER=",vfilter=${VLC_VFILTER}"
else
    VLC_VFILTER=""
fi

if [ -n "$VLC_VIDEO_CODEC" ]; then
    VLC_VIDEO_CODEC=",vcodec=${VLC_VIDEO_CODEC}"
else
    VLC_VIDEO_CODEC=""
fi

if [ -n "$VLC_AUDIO_CODEC" ]; then
    VLC_AUDIO_CODEC=",acodec=${VLC_AUDIO_CODEC}"
else
    VLC_AUDIO_CODEC=""
fi

if [ -n "$VLC_DESTINATION" ]; then
    VLC_DESTINATION=",dst=${VLC_DESTINATION}"
else
    VLC_DESTINATION=""
fi

if [ -n "$VLC_X264" ]; then
    VLC_X264="${VLC_VENC}{${VLC_X264}}"
else
    VLC_X264=""
fi

if [ -n "$VLC_VENC" ]; then
    VLC_VENC=",venc=${VLC_X264}"
else
    VLC_VENC=""
fi

if [ -n "$VLC_AENC" ]; then
    VLC_AENC=",aenc=${VLC_AENC}"
else
    VLC_AENC=""
fi

if [ -n "$VLC_SCALE" ]; then
    VLC_SCALE=",scale=${VLC_SCALE}"
else
    VLC_SCALE=""
fi

if [ -n "$VLC_THREADS" ]; then
    VLC_THREADS=",threads=${VLC_THREADS}"
else
    VLC_THREADS=""
fi

if [ -n "$VLC_AUDIO_BITRATE" ]; then
    VLC_AUDIO_BITRATE=",ab=${VLC_AUDIO_BITRATE}"
else
    VLC_AUDIO_BITRATE=""
fi

if [ -n "$VLC_AUDIO_CHANNELS" ]; then
    VLC_AUDIO_CHANNELS=",channels=${VLC_AUDIO_CHANNELS}"
else
    VLC_AUDIO_CHANNELS=""
fi

if [ -n "$VLC_AUDIO_SAMPLERATE" ]; then
    VLC_AUDIO_SAMPLERATE=",samplerate=${VLC_AUDIO_SAMPLERATE}"
else
    VLC_AUDIO_SAMPLERATE=""
fi

if [ -n "$VLC_FPS" ]; then
    VLC_FPS=",fps=${VLC_FPS}"
else
    VLC_FPS=""
fi

if [ -n "$VLC_BITRATE" ]; then
    VLC_BITRATE=",vb=${VLC_BITRATE}"
else
    VLC_BITRATE=""
fi

if [ -n "$VLC_ADAPTIVE_WIDTH" ]; then
    VLC_WIDTH=",width=${VLC_ADAPTIVE_WIDTH}"
else
    VLC_WIDTH=""
fi

if [ -n "$VLC_ADAPTIVE_HEIGHT" ]; then
    VLC_HEIGHT=",height=${VLC_ADAPTIVE_HEIGHT}"
else
    VLC_HEIGHT=""
fi

SOUT="#transcode{${VLC_THREADS}${VLC_VENC}${VLC_AENC}${VLC_SCALE}${VLC_VIDEO_CODEC}${VLC_AUDIO_CODEC}${VLC_AUDIO_BITRATE}${VLC_AUDIO_SAMPLERATE}${VLC_AUDIO_CHANNELS}${VLC_FPS}${VLC_BITRATE}${VLC_AFILTER}${VLC_SFILTER}${VLC_VFILTER}${VLC_WIDTH}${VLC_HEIGHT}}:duplicate{${VLC_DESTINATION}}"

VLC_COMMAND=( "-I" "telnet" "--no-media-library" "--verbose" "${VLC_VERBOSE}" "--no-disable-screensaver" "--extraintf" "rc" "--rc-host" "127.0.0.1:${VLC_RC_PORT}" "${VLC_AVCODEC_OPTIONS[@]}" "--no-repeat" "--no-loop" "--network-caching" "${VLC_CACHE}" "--telnet-password" "${PASSWORD}" "--telnet-port" "${PORT}" "--drop-late-frames" "--skip-frames" "--play-and-exit" "--no-daemon" "--adaptive-logic" "${VLC_ADAPTIVE_LOGIC}" "--adaptive-maxwidth" "${VLC_ADAPTIVE_WIDTH}" "--adaptive-maxheight" "${VLC_ADAPTIVE_HEIGHT}" "--adaptive-bw" "${VLC_ADAPTIVE_BITRATE}" "${VLC_EXTRA_OPTIONS_AUDIO_FILTER[@]}" "--sout" "${SOUT}" "${VLC_SOURCE_URL}" "vlc://quit" )
# VLC_COMMAND="${VLC} -I telnet --no-media-library --verbose=${VLC_VERBOSE} --no-disable-screensaver --extraintf=rc --rc-host=127.0.0.1:${VLC_RC_PORT} ${VLC_AVCODEC_OPTIONS} --no-repeat --no-loop --network-caching=${VLC_CACHE} --telnet-password=${PASSWORD} --telnet-port=${PORT} --drop-late-frames --skip-frames --play-and-exit --no-daemon --adaptive-logic=${VLC_ADAPTIVE_LOGIC} --adaptive-maxwidth=${VLC_ADAPTIVE_WIDTH} --adaptive-maxheight=${VLC_ADAPTIVE_HEIGHT} --adaptive-bw=${VLC_ADAPTIVE_BITRATE} ${VLC_EXTRA_OPTIONS_AUDIO_FILTER} --sout=${SOUT} ${VLC_SOURCE_URL} vlc://quit"
echo "📺 Starting VLC Multicast ${VLC_SOURCE_URL} as ${VLC_SAP_GROUP}/${VLC_SAP_NAME} rtp://@${VLC_MULTICAST_IP}:${VLC_MULTICAST_PORT}"
echo "🖥 ${VLC_COMMAND[@]}"
# shellcheck disable=SC2086
nice -n -20 ${VLC} "${VLC_COMMAND[@]}" &
vlcpid=$!
echo "🆔 VLC Running as PID ${vlcpid}"
wait "$vlcpid"
rm -f "${HOME}"/vlc/mosaic.vlm
echo "👋 Finished VLC Multicast rtp://@${VLC_MULTICAST_IP}:${VLC_MULTICAST_PORT}"
